apiVersion: v1
kind: Service
metadata:
  name: java-function-service
spec:
  type: LoadBalancer       # Change from NodePort to LoadBalancer
  selector:
    app: java-function-app
  ports:
    - protocol: TCP
      port: 80            # External port (LoadBalancer)
      targetPort: 80      # Container port
      # Remove nodePort field here for LoadBalancer type

